name: Update Weather Data
on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Disable default credentials

      - name: Create data folder if missing
        run: mkdir -p data  # Ensure "data" directory exists

      - name: Fetch Weather Data
        run: curl -sS "https://script.google.com/macros/s/AKfycbx1SgDH33eWMDWywwaObK7-uFkfw4UE2I5H9dAfaxG7xKWslwkXziq9QYrOMWekLfpI/exec" -o data/weather.json

      - name: Debug JSON Output
        run: cat data/weather.json
        
      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Use the secret
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/weather.json
          git commit -m "Updated Weather Data" || echo "No changes"
          git push https://x-access-token:${GH_PAT}@github.com/Arwond/weather-data-pretty.git main

